### ISSUE TITLE
initial settings

### ISSUE THREAD

**Issue by kljopu** [nest-excalibur/google-cloud-vision#2]
Hi, im trying to use in my service struggling with initial setting

you mentioned in READ.md like "Don't forget to export your google-cloud credentials before start the server."

could you provide some example code?

**Comment by velascoandres** [comment]
@kljopu 
 The google credentials means the google service account file. This file should be exported like the following example: 

```shell
export GOOGLE_APPLICATION_CREDENTIALS="/home/user/Downloads/service-account-file.json"
```
you can check it on the google cloud docs
https://cloud.google.com/docs/authentication/getting-started#linux-or-macos

Also you can export this credentials through an environment file (.env)

```txt
GOOGLE_APPLICATION_CREDENTIALS=/home/user/Downloads/service-account-file.json
```
